alias: Daily Battery Check
description: Checks all battery-powered devices and creates RT tickets for any below threshold
triggers:
  - at: "09:00:00"
    trigger: time
actions:
  - variables:
      threshold: 30
  - variables:
      low_battery_sensors: >
        {% set ns = namespace(sensors=[]) %}
        {% for state in states.sensor %}
          {% if state.attributes.device_class == 'battery'
             and state.state not in ['unknown', 'unavailable']
             and state.state | int(0) < threshold %}
            {% set ns.sensors = ns.sensors + [{'entity_id': state.entity_id, 'name': state.name, 'level': state.state}] %}
          {% endif %}
        {% endfor %}
        {{ ns.sensors }}
  - repeat:
      for_each: "{{ low_battery_sensors }}"
      sequence:
        - variables:
            device_id: "{{ device_id(repeat.item.entity_id) }}"
        - condition: template
          value_template: "{{ device_id is not none and device_id != '' }}"
        - action: ha_rt.create_ticket
          data:
            device_id: "{{ device_id }}"
            subject: "Low battery: {{ repeat.item.name }}"
            text: >
              Battery level for {{ repeat.item.name }} is at {{ repeat.item.level }}%,
              below the threshold of {{ threshold }}%.

              Entity: {{ repeat.item.entity_id }}
